import Header from '@/components/Header/Header'
import Provider from '@/components/Provider'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Diễn Đàn Huyền Học',
  description: 'Generated by create next app',
}

export default function DefaultLayout({ children }) {
  return (
    <div className='root'>
      <Header></Header>
      {children}
    </div>
  )
}
