import Provider from '@/components/Provider'
import db from '@/config/database/index'
import './globals.scss'

export const metadata = {
  title: 'Diễn Đàn Huyền Học',
  description: 'Generated by create next app',
}



export default async function RootLayout({ children }) {
  await db.connect();
  return (
    <html lang="en">
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
